def generate_report(findings, score, level):
    """
    Generate a human-readable RazorGuard-AI security report.

    The report summarizes:
    - Overall risk level
    - Overall risk score
    - Number of findings
    - Individual security findings
    - Severity and category
    - Score contribution
    - Recommended action
    """

    report = []

    # =========================================================
    # Header
    # =========================================================

    report.append("=" * 50)
    report.append("        RAZORGUARD-AI SECURITY REPORT")
    report.append("=" * 50)
    report.append("")

    # =========================================================
    # Risk Summary
    # =========================================================

    report.append("RISK SUMMARY")
    report.append("-" * 50)

    report.append(f"Risk Level     : {level}")
    report.append(f"Risk Score     : {score}/100")
    report.append(f"Total Findings : {len(findings)}")
    report.append("")

    # =========================================================
    # Risk Interpretation
    # =========================================================

    if level == "CRITICAL":
        interpretation = (
            "Critical security indicators detected. "
            "Immediate investigation is recommended."
        )

    elif level == "HIGH":
        interpretation = (
            "High-risk security indicators detected. "
            "Further investigation is recommended."
        )

    elif level == "MEDIUM":
        interpretation = (
            "Suspicious activity detected. "
            "Review the findings carefully."
        )

    elif level == "LOW":
        interpretation = (
            "Low-risk indicators detected. "
            "No immediate action may be required."
        )

    else:
        interpretation = (
            "No significant security indicators were detected."
        )

    report.append(f"Assessment    : {interpretation}")
    report.append("")

    # =========================================================
    # Findings
    # =========================================================

    report.append("FINDINGS")
    report.append("-" * 50)

    if findings:

        for index, finding in enumerate(findings, start=1):

            keyword = finding.get("keyword", "Unknown")
            severity = finding.get("severity", "UNKNOWN")
            finding_type = finding.get("type", "unknown")
            category = finding.get("category", "unknown")
            contribution = finding.get(
                "score_contribution",
                "N/A"
            )

            report.append(f"{index}. {keyword}")
            report.append(f"   Severity          : {severity}")
            report.append(f"   Type              : {finding_type}")
            report.append(f"   Category          : {category}")
            report.append(
                f"   Score Contribution: {contribution}"
            )
            report.append("")

    else:

        report.append("No security findings detected.")
        report.append("")

    # =========================================================
    # Recommended Action
    # =========================================================

    report.append("RECOMMENDED ACTION")
    report.append("-" * 50)

    if level == "CRITICAL":

        report.append(
            "Investigate the detected activity immediately "
            "and isolate affected systems if necessary."
        )

    elif level == "HIGH":

        report.append(
            "Review the detected activity and verify that "
            "the requested or observed behavior is authorized."
        )

    elif level == "MEDIUM":

        report.append(
            "Review the findings and determine whether the "
            "activity is expected or legitimate."
        )

    elif level == "LOW":

        report.append(
            "Continue normal monitoring and review the "
            "finding if additional context becomes available."
        )

    else:

        report.append(
            "No immediate security action is recommended."
        )

    report.append("")

    # =========================================================
    # Footer
    # =========================================================

    report.append("=" * 50)
    report.append("Generated by RazorGuard-AI")
    report.append("=" * 50)

    return "\n".join(report)